/*
 * This software is public domain software, however it is preferred
 * that the following disclaimers be attached.
 * Software Copywrite/Warranty Disclaimer
 * 
 * This software was developed at the National Institute of Standards and
 * Technology by employees of the Federal Government in the course of their
 * official duties. Pursuant to title 17 Section 105 of the United States
 * Code this software is not subject to copyright protection and is in the
 * public domain.
 * 
 * This software is experimental. NIST assumes no responsibility whatsoever 
 * for its use by other parties, and makes no guarantees, expressed or 
 * implied, about its quality, reliability, or any other characteristic. 
 * We would appreciate acknowledgement if the software is used. 
 * This software can be redistributed and/or modified freely provided 
 * that any derivative works bear some notice that they are derived from it, 
 * and any modified versions bear some notice that they have been modified.
 * 
 *  See http://www.copyright.gov/title17/92chap1.html#105
 * 
 */
package aprs.framework;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Will Shackleford {@literal <william.shackleford@nist.gov>}
 */
public class LauncherJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LauncherJFrame
     */
    public LauncherJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPrevMulti = new javax.swing.JButton();
        jButtonNewMulti = new javax.swing.JButton();
        jButtonPrevMulti2 = new javax.swing.JButton();
        jButtonPrevSingle = new javax.swing.JButton();
        jButtonPrevMulti4 = new javax.swing.JButton();
        jButtonOpenMulti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APRS Launcher");
        setResizable(false);

        jButtonPrevMulti.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButtonPrevMulti.setText("Previous Multi Workspace Supervisor System");
        jButtonPrevMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevMultiActionPerformed(evt);
            }
        });

        jButtonNewMulti.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButtonNewMulti.setText("New Multi Workspace Supervisor System");
        jButtonNewMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewMultiActionPerformed(evt);
            }
        });

        jButtonPrevMulti2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButtonPrevMulti2.setText("New Single Workspace System");
        jButtonPrevMulti2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevMulti2ActionPerformed(evt);
            }
        });

        jButtonPrevSingle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButtonPrevSingle.setText("Previous Single Workspace System");
        jButtonPrevSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevSingleActionPerformed(evt);
            }
        });

        jButtonPrevMulti4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButtonPrevMulti4.setText("Open Single Workspace System");
        jButtonPrevMulti4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevMulti4ActionPerformed(evt);
            }
        });

        jButtonOpenMulti.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButtonOpenMulti.setText("Open Multi Workspace Supervisor System");
        jButtonOpenMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenMultiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPrevMulti4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrevMulti2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrevSingle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOpenMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrevMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonNewMulti, jButtonOpenMulti, jButtonPrevMulti, jButtonPrevMulti2, jButtonPrevMulti4, jButtonPrevSingle});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPrevMulti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewMulti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpenMulti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrevSingle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrevMulti2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrevMulti4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonNewMulti, jButtonOpenMulti, jButtonPrevMulti, jButtonPrevMulti2, jButtonPrevMulti4, jButtonPrevSingle});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrevMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevMultiActionPerformed
        AprsMulitSupervisorJFrame amsFrame = new AprsMulitSupervisorJFrame();
        amsFrame.startColorTextReader();
        amsFrame.loadPrevSetup();
        amsFrame.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonPrevMultiActionPerformed

    private void jButtonNewMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewMultiActionPerformed
        AprsMulitSupervisorJFrame amsFrame = new AprsMulitSupervisorJFrame();
        amsFrame.startColorTextReader();
        amsFrame.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNewMultiActionPerformed

    private void jButtonOpenMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenMultiActionPerformed
        AprsMulitSupervisorJFrame amsFrame = new AprsMulitSupervisorJFrame();
        amsFrame.startColorTextReader();
        amsFrame.setVisible(true);
        this.setVisible(false);
        amsFrame.browseOpenSetup();
        this.dispose();
    }//GEN-LAST:event_jButtonOpenMultiActionPerformed

    private void jButtonPrevSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevSingleActionPerformed
        AprsJFrame aFrame = new AprsJFrame();
        aFrame.defaultInit();
        aFrame.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonPrevSingleActionPerformed

    private void jButtonPrevMulti2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevMulti2ActionPerformed
       AprsJFrame aFrame = new AprsJFrame();
        aFrame.emptyInit();
        aFrame.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonPrevMulti2ActionPerformed

    private void jButtonPrevMulti4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevMulti4ActionPerformed
        AprsJFrame aFrame = new AprsJFrame();
        aFrame.emptyInit();
        aFrame.setVisible(true);
        this.setVisible(false);
        aFrame.browseOpenPropertiesFile();
        this.dispose();
    }//GEN-LAST:event_jButtonPrevMulti4ActionPerformed

    private void checkFiles() {
        File f = AprsJFrame.getDefaultPropertiesFile();
        if(f != null && f.exists()) {
            try {
                jButtonPrevSingle.setToolTipText("Open "+f.getCanonicalPath()+" . . .");
                jButtonPrevSingle.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(LauncherJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jButtonPrevSingle.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LauncherJFrame lFrame = new LauncherJFrame();
                lFrame.checkFiles();
                lFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewMulti;
    private javax.swing.JButton jButtonOpenMulti;
    private javax.swing.JButton jButtonPrevMulti;
    private javax.swing.JButton jButtonPrevMulti2;
    private javax.swing.JButton jButtonPrevMulti4;
    private javax.swing.JButton jButtonPrevSingle;
    // End of variables declaration//GEN-END:variables
}
