/*
 * This software is public domain software, however it is preferred
 * that the following disclaimers be attached.
 * Software Copywrite/Warranty Disclaimer
 * 
 * This software was developed at the National Institute of Standards and
 * Technology by employees of the Federal Government in the course of their
 * official duties. Pursuant to title 17 Section 105 of the United States
 * Code this software is not subject to copyright protection and is in the
 * public domain.
 * 
 * This software is experimental. NIST assumes no responsibility whatsoever 
 * for its use by other parties, and makes no guarantees, expressed or 
 * implied, about its quality, reliability, or any other characteristic. 
 * We would appreciate acknowledgement if the software is used. 
 * This software can be redistributed and/or modified freely provided 
 * that any derivative works bear some notice that they are derived from it, 
 * and any modified versions bear some notice that they have been modified.
 * 
 *  See http://www.copyright.gov/title17/92chap1.html#105
 * 
 */
package aprs.framework.database;

import aprs.framework.AprsJFrame;
import java.io.File;

/**
 *
 * @author Will Shackleford {@literal <william.shackleford@nist.gov>}
 */
public class DbSetupJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DbSetupJInternalFrame
     */
    @SuppressWarnings("initialization")
    public DbSetupJInternalFrame() {
        initComponents();
    }

    /**
     * Load the most recent settings file.
     */
    public void loadRecentSettings() {
        dbSetupJPanel1.loadRecentSettings();
    }

    /**
     * Set the value of aprsJFrame
     *
     * @param aprsJframe new value of aprsJFrame
     */
    public void setAprsJframe(AprsJFrame aprsJframe) {
        dbSetupJPanel1.setAprsJFrame(aprsJframe);
    }

    /**
     * Get name of a script file to execute to start the database server if available
     * @return name of start script file
     */
    public String getStartScript() {
        return dbSetupJPanel1.getStartScript();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbSetupJPanel1 = new aprs.framework.database.DbSetupJPanel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Database Setup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbSetupJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbSetupJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Get a source for future database setup information.
     * @return database setup publisher
     */
    public DbSetupPublisher getDbSetupPublisher() {
        return this.dbSetupJPanel1;
    }

    /**
     * Set the properties file   
     * @param f new value of propertiesFile
     */
    public void setPropertiesFile(File f) {
        dbSetupJPanel1.setPropertiesFile(f);
    }

    /**
     * Get the current properties file.
     * @return properties file
     */
    public File getPropertiesFile() {
        return dbSetupJPanel1.getPropertiesFile();
    }

    public void shutDownNotifyService() {
        dbSetupJPanel1.shutDownNotifyService();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aprs.framework.database.DbSetupJPanel dbSetupJPanel1;
    // End of variables declaration//GEN-END:variables
}
