/*
 * This software is public domain software, however it is preferred
 * that the following disclaimers be attached.
 * Software Copywrite/Warranty Disclaimer
 * 
 * This software was developed at the National Institute of Standards and
 * Technology by employees of the Federal Government in the course of their
 * official duties. Pursuant to title 17 Section 105 of the United States
 * Code this software is not subject to copyright protection and is in the
 * public domain.
 * 
 * This software is experimental. NIST assumes no responsibility whatsoever 
 * for its use by other parties, and makes no guarantees, expressed or 
 * implied, about its quality, reliability, or any other characteristic. 
 * We would appreciate acknowledgement if the software is used. 
 * This software can be redistributed and/or modified freely provided 
 * that any derivative works bear some notice that they are derived from it, 
 * and any modified versions bear some notice that they have been modified.
 * 
 *  See http://www.copyright.gov/title17/92chap1.html#105
 * 
 */
package aprs.framework.colortextdisplay;

import aprs.framework.Utils;
import aprs.framework.database.SocketLineReader;
import java.awt.Color;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;

/**
 *
 * @author shackle
 */
public class ColorTextJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ColorTextJPanel
     */
    public ColorTextJPanel() {
        try {
            initComponents();
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

    /**
     * Creates new form ColorTextJPanel
     */
    public void setLabelsAndIcons(String label1, Icon img1, String label2, Icon img2) {
        try {
            jLabelRobotText1.setText(label1);
            jLabelRobotText2.setText(label2);
            jLabelRobotIcon1.setIcon(img1);
            jLabelRobotIcon2.setIcon(img2);
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
    
    private static final Class THIS_CLASS = aprs.framework.colortextdisplay.ColorTextJPanel.class;
    
    public static Icon getRobotIcon(String name) {
        if(name == null || name.length() < 1) {
            return null;
        }
        if(name.toUpperCase().contains("MOTOMAN")) {
            return new javax.swing.ImageIcon(THIS_CLASS.getResource("/aprs/framework/screensplash/motoman_small.png"));
        } else if(name.toUpperCase().contains("FANUC")) {
            return new javax.swing.ImageIcon(THIS_CLASS.getResource("/aprs/framework/screensplash/fanuc_small.png"));
        } else {
            return new javax.swing.ImageIcon(THIS_CLASS.getResource("/aprs/framework/screensplash/"+name.toLowerCase()+"_small.png"));
        }
    }
    
    
    public static final int COLORTEXT_SOCKET_PORT = 23444;

    private SocketLineReader reader;

    public void startReader() {
        SocketLineReader readerTmp = null;
        try {
            readerTmp = SocketLineReader.startServer(COLORTEXT_SOCKET_PORT, "ColorTextServer", this::parseSocketLine);

        } catch (IOException ex) {
            Logger.getLogger(ColorTextJFrame.class.getName()).log(Level.SEVERE, "Failed to bind color text socket port: " + COLORTEXT_SOCKET_PORT, ex);
        }
        this.reader = readerTmp;
    }

    public void stopReader() {
        if (null != reader) {
            reader.close();
            reader = null;
        }
    }

    private void parseSocketLine(String line, PrintStream ps) {
        String colorStrings[] = line.split("[ \t,]+");
        ps.println(Arrays.toString(colorStrings));
        if (colorStrings.length != 2) {
            ps.println("2 colors expected : line " + line);
            System.err.println("2 colors expected : line=" + line);
            return;
        }
        Color color1 = Color.decode(colorStrings[1]);
        ps.println("color1 = " + color1);
        Color color2 = Color.decode(colorStrings[0]);
        ps.println("color2 = " + color2);
        Utils.runOnDispatchThread(() -> {
            jPanel1.setBackground(color1);
            jPanel2.setBackground(color2);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelRobotText1 = new javax.swing.JLabel();
        jLabelRobotIcon1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelRobotText2 = new javax.swing.JLabel();
        jLabelRobotIcon2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelRobotText1.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLabelRobotText1.setText("Motoman");

        jLabelRobotIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aprs/framework/screensplash/motoman_small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelRobotText1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelRobotIcon1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRobotText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRobotIcon1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelRobotText2.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLabelRobotText2.setText("Fanuc");

        jLabelRobotIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aprs/framework/screensplash/fanuc_small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRobotText2)
                    .addComponent(jLabelRobotIcon2))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelRobotText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRobotIcon2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelRobotIcon1;
    private javax.swing.JLabel jLabelRobotIcon2;
    private javax.swing.JLabel jLabelRobotText1;
    private javax.swing.JLabel jLabelRobotText2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
