/*
 * This software is public domain software, however it is preferred
 * that the following disclaimers be attached.
 * Software Copywrite/Warranty Disclaimer
 * 
 * This software was developed at the National Institute of Standards and
 * Technology by employees of the Federal Government in the course of their
 * official duties. Pursuant to title 17 Section 105 of the United States
 * Code this software is not subject to copyright protection and is in the
 * public domain.
 * 
 * This software is experimental. NIST assumes no responsibility whatsoever 
 * for its use by other parties, and makes no guarantees, expressed or 
 * implied, about its quality, reliability, or any other characteristic. 
 * We would appreciate acknowledgement if the software is used. 
 * This software can be redistributed and/or modified freely provided 
 * that any derivative works bear some notice that they are derived from it, 
 * and any modified versions bear some notice that they have been modified.
 * 
 *  See http://www.copyright.gov/title17/92chap1.html#105
 * 
 */
package aprs.framework.pddl.executor;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Will Shackleford {@literal <william.shackleford@nist.gov>}
 */
public class PositionMapJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PositionMapJPanel
     */
    public PositionMapJPanel() {
        initComponents();
        defaultBackgroundColor = this.getBackground();
        defaultForegroundColor = this.getForeground();
    }

    private final Color defaultBackgroundColor;
    private final Color defaultForegroundColor;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextFieldErrorMapFilename = new javax.swing.JTextField();
        jButtonErrorMapFileBrowse = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSave = new javax.swing.JButton();
        jSpinnerIndex = new javax.swing.JSpinner();
        jButtonClear = new javax.swing.JButton();

        jLabel13.setText("File name:");

        jTextFieldErrorMapFilename.setText("errors.csv");

        jButtonErrorMapFileBrowse.setText("Browse");
        jButtonErrorMapFileBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErrorMapFileBrowseActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Double(0.0),  new Double(0.0),  new Double(0.0),  new Double(0.0),  new Double(0.0),  new Double(0.0)},
                { new Double(1.0),  new Double(0.0),  new Double(0.0),  new Double(1.0),  new Double(0.0),  new Double(0.0)},
                { new Double(0.0),  new Double(1.0),  new Double(0.0),  new Double(0.0),  new Double(1.0),  new Double(0.0)},
                { new Double(0.0),  new Double(0.0),  new Double(1.0),  new Double(0.0),  new Double(0.0),  new Double(1.0)}
            },
            new String [] {
                "X", "Y", "Z", "Offset_X", "Offset_Y", "Offset_Z"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jSpinnerIndex.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));
        jSpinnerIndex.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIndexStateChanged(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldErrorMapFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonErrorMapFileBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClear)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jTextFieldErrorMapFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonErrorMapFileBrowse)
                        .addComponent(jButtonSave)
                        .addComponent(jButtonClear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    final private List<PositionMap> positionMaps = new ArrayList<>();

    public final List<PositionMap> getPositionMaps() {
        return Collections.unmodifiableList(positionMaps);
    }
    private List<PositionMap> reversePositionMaps = new ArrayList<>();

    public final List<PositionMap> getReversePositionMaps() {
        if (null == reversePositionMaps) {
            reversePositionMaps = new ArrayList<>();
            for (int i = positionMaps.size()-1; i >= 0 ; i--) {
                PositionMap pm = positionMaps.get(i);
                PositionMap rpm = pm.reverse();
                reversePositionMaps.add(rpm);
            }
        }
        return Collections.unmodifiableList(reversePositionMaps);
    }

    public PositionMap getPositionMap(int index) {
        return positionMaps.get(index);
    }

    public void setPositionMap(int index, PositionMap positionMap) {
        reversePositionMaps = null;
        while (positionMaps.size() <= index) {
            positionMaps.add(null);
        }
        positionMaps.set(index, positionMap);
        if (index == ((int) jSpinnerIndex.getValue())) {
            loadPositionMapToTable(positionMap);
        }
        jSpinnerIndex.setModel(new SpinnerNumberModel((int) jSpinnerIndex.getValue(), 0, positionMaps.size(), 1));
    }

    public void addPositionMap(PositionMap positionMap) {
        reversePositionMaps = null;
        this.positionMaps.add(positionMap);
        if (positionMaps.size() == 1) {
            loadPositionMapToTable(positionMap);
        }
        jSpinnerIndex.setModel(new SpinnerNumberModel((int) jSpinnerIndex.getValue(), 0, positionMaps.size(), 1));
    }

    public void removePositionMap(PositionMap positionMap) {
        reversePositionMaps = null;
        int spinVal = (int) jSpinnerIndex.getValue();
        String pfn = positionMap.getFileName();
        this.positionMaps.remove(positionMap);
        if (pfn != null && pfn.length() > 0) {
            for (int i = 0; i < positionMaps.size(); i++) {
                if (positionMaps.get(i).getFileName().equals(pfn)) {
                    positionMaps.remove(i);
                }
            }
        }
        if (spinVal < 0 || spinVal >= positionMaps.size()) {
            spinVal = 0;
        }
        if (positionMaps.size() < 1) {
            addPositionMap(PositionMap.emptyPositionMap());
        }
        loadPositionMapToTable(getPositionMap(spinVal));
        jSpinnerIndex.setModel(new SpinnerNumberModel(spinVal, 0, positionMaps.size(), 1));
    }

    private boolean selected;

    /**
     * Get the value of selected
     *
     * @return the value of selected
     */
    public boolean isSelected() {
        return selected;
    }

    /**
     * Set the value of selected
     *
     * @param selected new value of selected
     */
    public void setSelected(boolean selected) {
        this.selected = selected;
        if (selected) {
            this.setBackground(defaultBackgroundColor.darker());
            this.setForeground(this.defaultForegroundColor.brighter());
        } else {
            this.setBackground(defaultBackgroundColor);
            this.setForeground(this.defaultForegroundColor);
        }
    }

    private File positionMapFile = null;

    public File getPositionMapFile() {
        if (null != positionMapFile) {
            return positionMapFile;
        }
        return new File(jTextFieldErrorMapFilename.getText());
    }

    private void loadPositionMapToTable(PositionMap positionMap) {
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        m.setRowCount(0);
//        m.setColumnIdentifiers(positionMap.getColumnHeaders());
//        m.set
        jTextFieldErrorMapFilename.setText(positionMap.getFileName());
        for (Object a[] : positionMap.getTableIterable()) {
            m.addRow(a);
        }
    }

    public void addPositionMapFile(File f) throws IOException, PositionMap.BadErrorMapFormatException {
//        if (!Objects.equal(f, positionMapFile)) {
//            positionMap = new PositionMap(f);
//            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
//            m.setRowCount(0);
//            m.setColumnIdentifiers(positionMap.getColumnHeaders());
//            jTextFieldErrorMapFilename.setText(positionMap.getFileName());
//            if (f.exists()) {
//                positionMap.getErrmapStringsList().stream().skip(1).forEach(a -> m.addRow(a));
//            }
//        }
        addPositionMap(new PositionMap(f));
    }

    private void jButtonErrorMapFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErrorMapFileBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                setPositionMap((int) jSpinnerIndex.getValue(), new PositionMap(chooser.getSelectedFile()));
            } catch (IOException | PositionMap.BadErrorMapFormatException ex) {
                Logger.getLogger(PddlExecutorJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonErrorMapFileBrowseActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        JFileChooser chooser = new JFileChooser();
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                PositionMap positionMap = getPositionMap((int) jSpinnerIndex.getValue());
                File f = chooser.getSelectedFile();
                if (null == positionMap) {
                    positionMap = PositionMap.emptyPositionMap();
                }
                positionMap.saveFile(f);
            } catch (IOException ex) {
                Logger.getLogger(PddlExecutorJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jSpinnerIndexStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIndexStateChanged
        final int spinVal = (int) jSpinnerIndex.getValue();
        if (getPositionMaps().size() == spinVal) {
            setPositionMap(spinVal, PositionMap.emptyPositionMap());
        }
        loadPositionMapToTable(getPositionMap(spinVal));
    }//GEN-LAST:event_jSpinnerIndexStateChanged

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        clearCurrentMap();
    }//GEN-LAST:event_jButtonClearActionPerformed

    public void clearCurrentMap() {
        final int spinVal = (int) jSpinnerIndex.getValue();
        setPositionMap(spinVal, PositionMap.emptyPositionMap());
        loadPositionMapToTable(getPositionMap(spinVal));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonErrorMapFileBrowse;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerIndex;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldErrorMapFilename;
    // End of variables declaration//GEN-END:variables
}
