/*
 * This software is public domain software, however it is preferred
 * that the following disclaimers be attached.
 * Software Copywrite/Warranty Disclaimer
 * 
 * This software was developed at the National Institute of Standards and
 * Technology by employees of the Federal Government in the course of their
 * official duties. Pursuant to title 17 Section 105 of the United States
 * Code this software is not subject to copyright protection and is in the
 * public domain.
 * 
 * This software is experimental. NIST assumes no responsibility whatsoever 
 * for its use by other parties, and makes no guarantees, expressed or 
 * implied, about its quality, reliability, or any other characteristic. 
 * We would appreciate acknowledgement if the software is used. 
 * This software can be redistributed and/or modified freely provided 
 * that any derivative works bear some notice that they are derived from it, 
 * and any modified versions bear some notice that they have been modified.
 * 
 *  See http://www.copyright.gov/title17/92chap1.html#105
 * 
 */
package aprs.framework.process.launcher;

import aprs.framework.logdisplay.LogDisplayJPanel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author shackle
 */
public class ProcessLauncherJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProcessLauncherJFrame
     */
    public ProcessLauncherJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProcesses = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneProcesses, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneProcesses, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        close();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcessLauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcessLauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcessLauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcessLauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    ProcessLauncherJFrame frm = new ProcessLauncherJFrame();
                    frm.addProcess("C:\\Users\\Public\\Documents\\APRS_AntVision_2018_03_06\\VideoTeachTable.exe");
//                    frm.addProcess("C:\\Users\\shackle\\neo4j-community-2.3.11-motoman\\bin\\Neo4j.bat");
                    frm.addProcess("C:\\Users\\shackle\\neo4j-community-2.3.11-fanuc\\bin\\Neo4j.bat");
//                    frm.addProcess(new File("C:\\Users\\shackle\\neo4j-community-2.3.11-fanuc"),
//                            "C:\\Program Files (x86)\\Java\\jre1.8.0_144\\bin\\java.exe",
//                            "-DworkingDir=C:\\Users\\shackle\\neo4j-community-2.3.11-fanuc\\bin\\..",
//                            "-DconfigFile=conf\\neo4j-wrapper.conf",
//                            "-DserverClasspath=lib/*.jar;system/lib/*.jar;plugins/**/*.jar;./conf*",
//                            "-DserverMainClass=org.neo4j.server.CommunityBootstrapper",
//                            "-jar",
//                            "C:\\Users\\shackle\\neo4j-community-2.3.11-fanuc\\bin\\windows-service-wrapper-5.jar"
//                    );

//                            "C:\\Program Files\\Java\\jdk1.8.0_92\\jre\\bin\\java.exe","-DworkingDir=C:\\Users\\shackle\\neo4j-community-2.3.11-fanuc\\bin\\..","-DconfigFile=conf\\neo4j-wrapper.conf","-DserverClasspath=lib/*.jar;system/lib/","..");
                    frm.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ProcessLauncherJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    static private class LogDisplayPanelOutputStream extends OutputStream {

        final private LogDisplayJPanel logDisplayJPanel;

        public LogDisplayPanelOutputStream(LogDisplayJPanel logDisplayJInternalFrame) {
            this.logDisplayJPanel = logDisplayJInternalFrame;
            if (null == logDisplayJInternalFrame) {
                throw new IllegalArgumentException("logDisplayJInteralFrame may not be null");
            }
        }

        private StringBuffer sb = new StringBuffer();

        @Override
        public void write(byte[] buf, int off, int len) {
            if (null != logDisplayJPanel) {
                final String s = new String(buf, off, len);
                sb.append(s);
                if (s.contains("\n")) {
                    String fullString = sb.toString();
                    if (javax.swing.SwingUtilities.isEventDispatchThread()) {
                        logDisplayJPanel.appendText(fullString);
                    } else {

                        javax.swing.SwingUtilities.invokeLater(new Runnable() {
                            @Override
                            public void run() {
                                logDisplayJPanel.appendText(fullString);
                            }
                        });
                    }
                    sb = new StringBuffer();
                }
            }
        }

        @Override
        public void write(int b) throws IOException {
            if (b < 0 || b > 255) {
                throw new IOException("bad byte = " + b);
            }
            byte buf[] = new byte[1];
            buf[0] = (byte) b;
            this.write(buf, 0, 1);
        }
    }
    private final List<WrappedProcess> processes = new ArrayList<>();

    public void addProcess(String... command) throws IOException {
        LogDisplayJPanel logPanel = new LogDisplayJPanel();
        String cmdLine = String.join(" ", command);
        this.jTabbedPaneProcesses.add(cmdLine, logPanel);
        OutputStream errPrintStream = new LogDisplayPanelOutputStream(logPanel);
        WrappedProcess wrappedProcess = new WrappedProcess(errPrintStream, errPrintStream, command);
        processes.add(wrappedProcess);
    }

    
     public void addProcess(List<String> command) throws IOException {
        LogDisplayJPanel logPanel = new LogDisplayJPanel();
        String cmdLine = String.join(" ", command);
        this.jTabbedPaneProcesses.add(cmdLine, logPanel);
        OutputStream errPrintStream = new LogDisplayPanelOutputStream(logPanel);
        WrappedProcess wrappedProcess = new WrappedProcess(errPrintStream, errPrintStream, command);
        processes.add(wrappedProcess);
    }
     
    public void addProcess(File directory, String... command) throws IOException {
        LogDisplayJPanel logPanel = new LogDisplayJPanel();
        String cmdLine = String.join(" ", command);
        this.jTabbedPaneProcesses.add(cmdLine, logPanel);
        OutputStream errPrintStream = new LogDisplayPanelOutputStream(logPanel);
        WrappedProcess wrappedProcess = new WrappedProcess(directory, errPrintStream, errPrintStream, command);
        processes.add(wrappedProcess);
    }
    
    public void addProcess(File directory, List<String> command) throws IOException {
        LogDisplayJPanel logPanel = new LogDisplayJPanel();
        String cmdLine = String.join(" ", command);
        this.jTabbedPaneProcesses.add(cmdLine, logPanel);
        OutputStream errPrintStream = new LogDisplayPanelOutputStream(logPanel);
        WrappedProcess wrappedProcess = new WrappedProcess(directory, errPrintStream, errPrintStream, command);
        processes.add(wrappedProcess);
    }

    public static List<String> parseCommandLine(String line) {
        List<String> args = new ArrayList<>();
        int dquotes = 0;
        int squotes = 0;
        StringBuilder sb = new StringBuilder();
        char lastC = 0;
        boolean isWindows = System.getProperty("os.name").startsWith("Windows");
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            switch (c) {
                case ' ':
                case '\t':
                    if (dquotes % 2 == 0 && squotes % 2 == 0 && lastC != '\\') {
                        args.add(sb.toString());
                        sb = new StringBuilder();
                    } else {
                        sb.append(c);
                    }
                    break;

                case '\"':
                    if (squotes % 2 == 0 && lastC != '\\') {
                        dquotes++;
                    } else {
                        sb.append(c);
                    }
                    break;

                case '\'':
                    if (dquotes % 2 == 0 && lastC != '\\') {
                        squotes++;
                    } else {
                        sb.append(c);
                    }
                    break;
                    
                case '\\':
                    if(lastC == '\\' || isWindows) {
                        sb.append(c);
                        c=0;
                    }
                    break;

                default:
                    sb.append(c);
                    break;
            }
            lastC = c;
        }
        String last = sb.toString();
        if(last.length() > 0) {
            args.add(last);
        }
        return args;
    }

    public void run(File f) throws IOException {
        try (BufferedReader br = new BufferedReader(new FileReader(f))) {
            String line;
            while (null != (line = br.readLine())) {
                addProcess(parseCommandLine(line));
            }
        }
    }

    public void close() {
        try {
            Neo4JKiller.killNeo4J();
        } catch (IOException ex) {
            Logger.getLogger(ProcessLauncherJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (WrappedProcess wp : processes) {
            wp.close();
        }
        this.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneProcesses;
    // End of variables declaration//GEN-END:variables
}
